# Generated by Django 3.1 on 2021-11-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210706_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
